### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by robinheghan** [ElmCast/elm-node#6]
I'm trying to use elm-node in my own application (writing elm backend), but I get the following error when using `elm package install`:

```
Error: There are no versions of package 'elmcast/elm-node' on your computer.
```

How do I work around this? (new elm user)

**Comment by mrmurphy** [comment]
@Skinney Did you figure out the answer? Is that why you closed the issue?

**Comment by robinheghan** [comment]
The package isn't published. So currently you have to manually include this in your application. This will probably improve when Elm get's proper support for native modules, which I believe is a goal for the next release.

**Comment by mrmurphy** [comment]
Thanks, that's what I ended up figuring out too :)
